---
- name: 'PROCESS | Resolve One Pinned Option Group'
  no_log: true
  vars:
    __plugin_groups__: >-
      {{ credential_resolver_option_groups
         | selectattr('plugin', 'equalto', __credential_resolver_attempt_profile__.plugin)
         | selectattr('canonical', 'equalto', credential_resolver_pin.key) | list }}
    __magic_groups__: >-
      {{ credential_resolver_option_groups
         | selectattr('plugin_type', 'equalto', 'magic')
         | selectattr('canonical', 'equalto', credential_resolver_pin.key) | list }}
  ansible.builtin.set_fact:
    __credential_resolver_pin_group__: >-
      {{ (__plugin_groups__ + __magic_groups__) | first }}

- name: 'PROCESS | Add One Pinned Option Group'
  no_log: true
  ansible.builtin.set_fact:
    __credential_resolver_attempt_map__: >-
      {{ __credential_resolver_attempt_map__
         | combine(dict(
             __credential_resolver_pin_group__.aliases
             | zip([credential_resolver_pin.value]
                   * (__credential_resolver_pin_group__.aliases | length))
           )) }}
