---
- name: 'Converge redhat_rocky_9'
  hosts: all
  become: true
  gather_facts: true
  vars:
    ENV: 'ci'
    redhat_rocky_9:
      audit:
        enabled: true
        reload: false
      audit_offload:
        enabled: true
        rsyslog_forward:
          remote_host: '198.51.100.10'
      aide:
        enabled: false
      fapolicyd:
        enabled: false
      grub_password:
        enabled: false
      evidence:
        enabled: false
      selinux:
        enabled: true
        mode: 'assert'
      fips:
        enabled: false
        mode: 'assert'
      mounts:
        enabled: false
        mode: 'assert'
      sysctl:
        reload: false
      packages:
        rng_tools:
          enabled: true
  roles:
    - role: 'RedHat_Rocky_9'
