---
- name: 'Prepare Rocky 9 molecule host'
  hosts: all
  become: true
  gather_facts: false
  tasks:

    - name: 'PREPARE | Install Role Prerequisites'
      ansible.builtin.dnf:
        name:
          - 'openssh-server'
          - 'policycoreutils-python-utils'
          - 'python3-dnf'
          - 'python3-libselinux'
          - 'sudo'
        state: 'present'

    - name: 'PREPARE | Generate SSH Host Keys'
      changed_when: false
      ansible.builtin.command:
        argv:
          - '/usr/bin/ssh-keygen'
          - '-A'

    - name: 'PREPARE | Enable sshd for Handler Validation'
      ansible.builtin.systemd_service:
        name: 'sshd'
        enabled: true
        state: 'started'
